### PR TITLE
Update AdultFanfiction.php

### PR DESCRIPTION
**Pull request by sirius16**
There was a problem due to a site update, but I believe I've resolved, want to try and make sure

### CODE REVIEW

**Comment by waylaidwanderer** [comment]
Sure, let me know if it works.

**Comment by RI45816** [comment]
Ah, unfortunately, it did not, I'd have to take a more trial and error approach, but I don't know how to test it on my own

**Comment by sirius16** [comment]
Ah, unfortunately, it did not, I'd have to take a more trial and error approach, but I don't know how to test it on my own

**Comment by sirius16** [comment]
Question, how would I go about setting this up locally so I can test improvements made to the code?

**Comment by waylaidwanderer** [comment]
You'll need something like XAMPP to set up a local webserver on your computer.

**Pull request merged**
