### PR TITLE
Cover generator

### PR DESCRIPTION
**Pull request by markomarkovic**
After getting frustrated with being unable to recognize the book base on the cover, added a simple cover generator.

### CODE REVIEW

**Comment by waylaidwanderer** [comment]
Hey, thanks for your contribution. Happy #hacktocker? :)

Instead of using prettier, I prefer to use eslint instead - I just haven't set it up since I wasn't expecting any contributions yet. You can remove your prettier config and I'll set up my eslint config after merging this in.

**Comment by markomarkovic** [comment]
Sure, no problem, I've pushed the change. I actually had this one in the pipeline for a long time (since Jan 22), #hacktober was an excuse to actually sit down and get the MVP out. Originally I planned to have several different cover styles with semi random colors/shapes/positioning (deterministically chosen based on the title/author), but then work got in the way and it got put on the back burner.
Let me know if you want help with anything else as It's a nice little service that's useful for a lot of people (me included) :)

**Comment by waylaidwanderer** [comment]
Thanks, appreciate it!

#hacktober changed the rules so it only counts repos with the hacktober topic, which I've just added to this repo. Mind checking to see if your pull request counted? https://hacktoberfest.digitalocean.com/profile

**Comment by markomarkovic** [comment]
It did, as it was submitted before they changed the rules. Thanks anyway.

image

**Comment by waylaidwanderer** [comment]
@markomarkovic I was just thinking - why don't we simply just skip adding the cover if it's the default image? AFAIK all the ebook readers should generate their own cover image (basically doing what this does) if it's missing one. That should solve the issue in a much simpler way, though I don't mind merging this in anyway - there's an opportunity to add a watermark for FicSave on the cover image with this.

**Pull request merged**
